# Generated by Django 4.1.7 on 2023-02-17 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_pensioncalculator_event_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='job_image',
            field=models.ImageField(default='default_job.jpg', upload_to='job_images/'),
        ),
        migrations.AddField(
            model_name='job_posting',
            name='job_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pensioncalculator',
            name='calculated_pension',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pensioncalculator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
