# Generated by Django 4.1.7 on 2023-02-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_job_posting_job_image_job_posting_job_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PensionCalculator',
        ),
    ]
