# Generated by Django 4.1.7 on 2023-02-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_pensioncalculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='hindi_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='hindi_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
